name: 'sign2'  # Your app name
type: 'php:8.1'  # PHP version to use

# Specify disk space for the app
disk: 512

# Web server configuration
web:
  locations:
    "/":
      root: "public"   # Ensure 'public' directory exists and has an 'index.php'
      index: "index.php"  # Default index page
      passthru: "/index.php"  # Handle all requests through index.php

# You can specify services (like databases) here if needed
services:
  db:
    type: 'mysql:5.7'
    disk: 512
    scope: 'project'

# Build instructions if necessary
build:
  flavor: 'php'
  commands:
    - composer install  # Install dependencies (if using Composer)

# Deployment commands if needed
deploy:
  commands:
    - echo "Deployment complete!"  # Custom deployment steps can be added here
