name: 'php-redirect-app'  # Name of the application, which you can customize.

type: 'php:8.1'  # The PHP runtime version to be used.

# Disk allocation for your app
disk: 512  # Adjust the disk size based on your needs

# Configure the web route section
web:
  locations:
    "/":
      root: "public"  # Define the directory containing your entry point, 'public' in this case.
      passthru: "/index.php"  # Forward all HTTP requests to 'index.php' in the 'public' directory.

# Build hook to install dependencies via Composer
hooks:
  build: |
    composer install --no-dev --optimize-autoloader  # Install PHP dependencies.

# Configuration for logging (Optional)
logs:
  access: /var/log/nginx/access.log
  error: /var/log/nginx/error.log

# Error handling or additional custom configurations can be added here (if needed).
