# Define the app
name: 'sign2'  # Replace with your app's name
type: 'php:7.4'  # Or the appropriate PHP version you're using

# Define the web route
web:
  disk: 512
  location: '/public'  # Assuming your app's public files are in the 'public' folder

# Custom Nginx configuration
nginx:
  # Root location and PHP handling
  locations:
    '/':
      root: 'web'  # Replace with the actual folder where your index.php or public files are
      try_files: ['$uri', '/index.php$is_args$args']  # Try to serve static files, then pass to PHP
    '~ \.php$':  # For PHP files
      fastcgi_pass: 'unix:/var/run/php/php7.4-fpm.sock'  # Adjust if you use a different PHP version
      fastcgi_index: 'index.php'
      fastcgi_param: 'SCRIPT_FILENAME $document_root$fastcgi_script_name'
      include: 'fastcgi_params'  # Ensure the default FastCGI params are included

  # Handling additional requests (if needed for your app)
  # You can define additional locations here if necessary, like for /assets or API endpoints
  locations:
    '/favicon.ico':  # You can adjust based on your needs
      try_files: ['$uri', '/index.php$is_args$args']

# Error and access logs
logs:
  access: /var/log/nginx/access.log
  error: /var/log/nginx/error.log

# The application will handle requests via index.php in the web root folder
# Adjust the paths according to where your index.php or application entry file is located
