name: 'sign2'  # Your app name
type: 'php:8.1'  # PHP version to use

# Specify disk space for the app
disk: 512

# Web server configuration
web:
  locations:
    "/":
      root: "public"  # Ensure 'public' directory exists and has an 'index.php'
      index: "index.php"  # Default index page
      passthru: "/index.php"  # Handle all requests through index.php

# Build instructions if necessary (optional)
build:
  flavor: 'php'

# If you're not using services (e.g., MySQL or others), remove this section
# services:
#   db:
#     type: 'mysql:5.7'
#     disk: 512
#     scope: 'project'

# Deployment commands if needed (optional)
# deploy:
#   commands:
#     - echo "Deployment complete!"
