name: app
type: php:8.2
web:
  locations:
    "/":
      root: "public"
      index: "index.php"  # Single index file, no array
      passthru: "/index.php"
      allow: true
      scripts: true
mounts:
  "/public": "public/"
  "/private": "private/"
runtime:
  extensions:
    - pdo
    - pdo_mysql
    - json
    - mbstring
    - tokenizer
    - curl
    - openssl
    - fileinfo
    - dom
hooks:
  build: |
    composer install --no-dev --optimize-autoloader
dependencies:
  php:
    composer/composer: '^2.0'
relationships:
  database: "mysql:mysql"
services:
  mysql:
    type: mysql:10.4
    disk: 1024
