name: app
type: php:8.1

build:
    flavor: composer

web:
    locations:
        "/":
            index: index.php  # This specifies the entry point of your application.
            allow: true
            passthru: "/index.php"

disk: 2048

mounts:
    "/uploads": "shared:files/uploads"

dependencies:
    php:
        ext-pdo: "*"
        ext-mbstring: "*"
