# .platform.app.yaml
name: app
type: php:8.2
web:
  locations:
    "/":
      root: "public"
      index: ["index.php", "index.html"] # Must be an array
      passthru: "/index.php"
      scripts: true
      allow: true
mounts:
  "/public": "public/"
  "/private": "private/"
runtime:
  extensions:
    - pdo
    - pdo_mysql
    - json
    - mbstring
    - tokenizer
    - curl
    - openssl
    - fileinfo
    - dom
hooks:
  build: |
    composer install --no-dev --optimize-autoloader
relationships:
  database: "mysql:mysql"
services:
  mysql:
    type: mysql:10.4
    disk: 1024
dependencies:
  php:
    composer/composer: '^2.0'
