name: app
type: php:8.1

build:
    flavor: composer

web:
    locations:
        "/":
            index:
                - index.php  # Use an array with "index.php" as the value.
            allow: true       # Optional: Allows public access to this path.
            passthru: "/index.php"  # Routes non-static requests to index.php.

disk: 2048

mounts:
    "/uploads": "shared:files/uploads"

dependencies:
    php:
        ext-pdo: "*"
        ext-mbstring: "*"
