# .platform.app.yaml

# The name of the application.
name: app

# The type of application.
type: php:8.2  # Adjust the PHP version as needed.

# Build and deploy configuration.
build:
    flavor: composer

# Web server configuration.
web:
    locations:
        "/":
            index: ["index.php"]
            scripts: true
            allow: true
            passthru: "/index.php"


# Disk storage.
disk: 1024  # Specify disk size in MB (e.g., 1024 MB = 1 GB)

# Dependencies for your application.
dependencies:
    php:
        ext-pdo: "*"
        ext-mbstring: "*"

# Mounts (if persistent storage is required).
mounts:
    "/storage": "shared:files"

# Runtime settings.
runtime:
    extensions:
        - pdo
        - mbstring

# Environment variables.
variables:
    env:
        APP_ENV: production
        APP_DEBUG: 0
