# Name of the application
name: 'sign2'

# Type of application and runtime
type: 'php:7.4'  # Change PHP version as needed

# Disk space allocation
disk: 512

# Web routing configuration
web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"

# PHP runtime and dependencies
runtime:
  extensions:
    - pdo_mysql
    - json
    - mbstring

# Dependencies
build:
  flavor: composer  # Use Composer to manage dependencies

# Mounts (for persistent files)
mounts:
  "/public/uploads": "shared:files/uploads"

# Relationships for external services
relationships:
  database: "mysql:db"

# Custom PHP settings (optional)
variables:
  php:
    memory_limit: "128M"
    upload_max_filesize: "10M"
    post_max_size: "10M"
    max_execution_time: "30"
